version: '3.8'
services:
  web:
    container_name: soap-srv-web
    build: .
    image: soaptubes-2:latest
    command: --default-authentication-plugin=mysql_native_password
    depends_on:
      - db
    ports:
      - "3003:3003"
    environment:
      - MYSQL_ROOT_PASSWORD=123456
      - MYSQL_DATABASE=mysql_database
      - MYSQL_USER=malik
      - MYSQL_PASSWORD=123456
      - USE_DOCKER_CONFIG=true
  db:
    container_name: db
    image: mysql
    restart: unless-stopped
    volumes:
      - ./migration/service-soap.sql:/docker-entrypoint-initdb.d/schema.sql:ro
      - ./mysql-data:/var/lib/mysql
    env_file:
      - .env
    environment:
      - MYSQL_ROOT_PASSWORD=123456
      - MYSQL_DATABASE=mysql_database
      - MYSQL_USER=malik
      - MYSQL_PASSWORD=123456
      - USE_DOCKER_CONFIG=true
    ports:
      - "9901:3306"
  phpmyadmin:
    container_name: soap-srv-pma
    image: phpmyadmin
    depends_on:
      - db
    environment:
      PMA_HOST: db
    restart: unless-stopped
    ports:
      - "4003:80"
