version: '3.7'

services:
  web:
    image: binotify-premium-app:latest
    volumes:
      - '.:/app'
      - '/app/node_modules'
    ports:
      - 3000:3000
    environment:
      - CHOKIDAR_USEPOLLING=true
